server:
  port: 6868
eureka:
  client:
    #是否需要注册到eureka
    register-with-eureka: false
    #是否从eureka中获取注册信息
    fetch-registry: false
    #Eureka客户端和Eureka服务端进行交互的地址
    service-url:
      #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/

